dist: trusty
sudo: required

language: cpp

env:
  -

matrix:
  include:
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#            - cmake3
#            - uuid-dev
#            #required for bdwgc
#            - autoconf
#            - libatomic-ops-dev
#            - libtool
#            - pkg-config
#      env:
#        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake3
            - uuid-dev
            #required for bdwgc
            - autoconf
            - libatomic-ops-dev
            - libtool
            - pkg-config
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

before_install:
    - eval "${MATRIX_EVAL}"

# Build steps
script:
 - $TRAVIS_BUILD_DIR/tools/build-all-release

#cache:
#  directories:
#    - externs

notifications:
 email:
    recipients:
      - anode.build@gmail.com
    on_success: always
    on_failure: always



