dist: trusty
sudo: required

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - clang++-4.0
            - cmake3
            - uuid-dev
            #required for bdwgc
            - autoconf
            - libatomic-ops-dev
            - libtool
            - pkg-config
            - libc++-dev  # this might not actually be required?

install:
 - export CC=clang-4.0 && export CXX=clang++-4.0 && export CMAKE_CXX_FLAGS="-std=c++14"

# Build steps
script:
 - $TRAVIS_BUILD_DIR/tools/build-all-release

cache:
  timeout: 600
  directories:
    - externs

notifications:
 email:
    recipients:
      - anode.build@gmail.com
    on_success: always
    on_failure: always

