dist: trusty
sudo: required

language: cpp

env:
  -

matrix:
  include:
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#            - cmake3
#            - uuid-dev
#            #required for bdwgc
#            - autoconf
#            - libatomic-ops-dev
#            - libtool
#            - pkg-config
#      env:
#        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - clang++-4.0
            - cmake3
            - uuid-dev
            #required for bdwgc
            - autoconf
            - libatomic-ops-dev
            - libtool
            - pkg-config
            - libc++-dev
#        env:
#          MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

#
#before_install:
#    - eval "${MATRIX_EVAL}"

install:
 - export CC=clang-4.0 && export CXX=clang++-4.0 && export CMAKE_CXX_FLAGS="-std=c++14"

# Build steps
script:
 - $TRAVIS_BUILD_DIR/tools/build-all-release

cache:
  timeout: 600
  directories:
    - externs

notifications:
 email:
    recipients:
      - anode.build@gmail.com
    on_success: always
    on_failure: always


