#!/bin/bash -e

SCRIPT_DIR=$(dirname $(readlink -f ${0}))
source $SCRIPT_DIR/util.sh

say "Building ANTLR4"
$SCRIPT_DIR/build-antlr4
say "Building LLVM"
$SCRIPT_DIR/build-llvm
say "Building linenoise-ng"
$SCRIPT_DIR/build-linenoise-ng
say "Building bdwgc"
$SCRIPT_DIR/build-bdwgc


