#!/bin/bash -eu

SCRIPT_DIR=$(dirname $(readlink -f ${0}))
PROJECT_ROOT_DIR=`readlink -f $SCRIPT_DIR/..`
source $SCRIPT_DIR/util.sh

#LWNN_INSTALL_DIR=$PROJECT_ROOT_DIR/target
LWNN_CMAKE_DIR=$PROJECT_ROOT_DIR/cmake-build

say "Directories:"
echo "PROJECT_ROOT_DIR  " $PROJECT_ROOT_DIR
echo "LWNN_CMAKE_DIR    " $LWNN_CMAKE_DIR
echo "NUM_CORES         " $NUM_CORES
#read -p "Press enter to continue"

say "Generating cmake cache"
mkdir -p $LWNN_CMAKE_DIR
cd $LWNN_CMAKE_DIR

cmake $PROJECT_ROOT_DIR 

set -e
say "Building LWNN"

cmake --build $LWNN_CMAKE_DIR -- -j $NUM_CORES

#say "Installing LWNN at" $LWNN_INSTALL_DIR
#rm -rf $LWNN_INSTALL_DIR
#cmake --build $LWNN_CMAKE_DIR --target install

#say "LWNN Built and Installed successfully at" $LWNN_INSTALL_DIR

say "Running Tests"
ctest --output-on-failure
ls

say "LWNN built and tested successfully!"