#!/bin/bash -e

SCRIPT_DIR=$(dirname $(readlink -f ${0}))
PROJECT_ROOT_DIR=`readlink -f $SCRIPT_DIR/..`
source $SCRIPT_DIR/util.sh

EXTERNS_DIR=$PROJECT_ROOT_DIR/externs
INSTALL_DIR=$EXTERNS_DIR/bdwgc/usr/local/lib
SCRATCH_DIR=$EXTERNS_DIR/scratch
SRC_DIR=$SCRATCH_DIR/bdwgc
BRANCH=master

say "Directories:"
echo "PROJECT_ROOT_DIR  " $PROJECT_ROOT_DIR
echo "EXTERNS_DIR       " $EXTERNS_DIR
echo "INSTALL_DIR       " $INSTALL_DIR
echo "SCRATCH_DIR       " $SCRATCH_DIR
echo "SRC_DIR           " $SRC_DIR
echo "CMAKE_DIR         " $CMAKE_DIR
echo "BRANCH            " $BRANCH
echo "NUM_CORES         " $NUM_CORES
#read -p "Press enter to continue"

mkdir -p $SCRATCH_DIR

# this part of the script, as crazy as it is, comes from the instructions on the bdwgc site: http://www.hboehm.info/gc/
cd $SCRATCH_DIR

say "Cloning or pulling github bdwgc"
if [ ! -d $SRC_DIR ]; then 
    git clone git://github.com/ivmai/bdwgc.git
    cd $SRC_DIR
else
    cd $SRC_DIR
    git pull
fi

#say "Cloning or pulling github libatomic_ops"
#if [! -d ./libatomic_ops ]; then 
#    git clone git://github.com/ivmai/libatomic_ops.git
#    cd $SRC_DIR
#else
#    cd $SRC_DIR
#    git pull
#fi




say "Running autoreconf -vif"
autoreconf -vif
say "Running automake --add-missing"
automake --add-missing
say "Running configure"
./configure --prefix=$INSTALL_DIR --enable-cplusplus --enable-parallel-mark
say "Running make check -j"
make check -j

say "Running make install"
make installl

say "bdwgc built and installed successfully at" $INSTALL_DIR

