#!/bin/bash -eu

SCRIPT_DIR=$(dirname $(readlink -f ${0}))
PROJECT_ROOT_DIR=`readlink -f $SCRIPT_DIR/..`
source $SCRIPT_DIR/util.sh

ANODE_CMAKE_DIR=$PROJECT_ROOT_DIR/cmake-build

say "Directories:"
echo "PROJECT_ROOT_DIR  " $PROJECT_ROOT_DIR
echo "ANODE_CMAKE_DIR   " $ANODE_CMAKE_DIR
echo "NUM_CORES         " $NUM_CORES

say "Generating cmake cache"
mkdir -p $ANODE_CMAKE_DIR
cd $ANODE_CMAKE_DIR

cmake $PROJECT_ROOT_DIR 

set -e
say "Building Anode"

cmake --build $ANODE_CMAKE_DIR -- -j $NUM_CORES

say "Running Tests"
ctest --output-on-failure
ls

say "ANODE built and tested successfully!"