#!/bin/bash -e

# required by anode and llvm
apt-get -y install cmake3 uuid-dev

# required by bdwgc
apt-get -y install autoconf libatomic-ops-dev libtool pkg-config

add-apt-repository ppa:ubuntu-toolchain-r/test
apt-get update
apt-get -y install clang++-4.0



# add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" -k https://apt.llvm.org/llvm-snapshot.gpg.key
# TODO add wget command to install key